apiVersion: v1
appVersion: '2021-12-10'
dependencies:
- name: common
  repository: file://../../../library/common/2112.0.0
  version: 2112.0.0
description: High Performance, Kubernetes Native Object Storage
home: https://min.io
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
keywords:
- mysql
- datebase
name: mysql
sources:
- https://github.com/minio/minio
- https://github.com/minio/charts
upstream_version: 8.0.5
version: 1.4.9
