## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
##
image:
  repository: mysql
  tag: 8.0.27
  pullPolicy: IfNotPresent

## Additional arguments to pass to minio binary
extraArgs: []

updateStrategy: RollingUpdate

service:
  nodePort: 23306

environment:
  ## Please refer for comprehensive list https://docs.minio.io/docs/minio-server-configuration-guide.html

appVolumeMounts:
  export:
    emptyDir: true
    mountPath: "/export"
